// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdptwtAamlQxRyslNrj7pWAbDCIO8IXk4',
    appId: '1:183858142740:web:97157d279ff34558071101',
    messagingSenderId: '183858142740',
    projectId: 'itwarbazar-b309c',
    authDomain: 'itwarbazar-b309c.firebaseapp.com',
    storageBucket: 'itwarbazar-b309c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNvTtF-2PUXpMDDH4ObFpDJJnQSIz56IY',
    appId: '1:183858142740:android:aedd10e78cd1d686071101',
    messagingSenderId: '183858142740',
    projectId: 'itwarbazar-b309c',
    storageBucket: 'itwarbazar-b309c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXO9Sqw1-dho2lgGgTL5VmCd5BqRS4H_E',
    appId: '1:183858142740:ios:0311d8c7a7ab2738071101',
    messagingSenderId: '183858142740',
    projectId: 'itwarbazar-b309c',
    storageBucket: 'itwarbazar-b309c.appspot.com',
    iosClientId: '183858142740-bk6g6lc2j629o5aul1a3hu6sb0jhct7v.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXO9Sqw1-dho2lgGgTL5VmCd5BqRS4H_E',
    appId: '1:183858142740:ios:0311d8c7a7ab2738071101',
    messagingSenderId: '183858142740',
    projectId: 'itwarbazar-b309c',
    storageBucket: 'itwarbazar-b309c.appspot.com',
    iosClientId: '183858142740-bk6g6lc2j629o5aul1a3hu6sb0jhct7v.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationPro',
  );
}
